services:
  php:
    build:
      context: .
      target: frankenphp_dev
    volumes:
      - ./:/app
      - /app/var
      - /app/vendor

  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "${MYSQL_PORT:-3306}:3306"
  ###< doctrine/doctrine-bundle ###
